app:
  modules: [api, ws, http, rtsp, mp4, hls, mjpeg]

rtsp:
  listen: ""

api:
  listen: "100.69.168.10:1984"
  username: "laba-vps"
  password: ${GO2RTC_API_PASSWORD}
  local_auth: true
  allow_paths:
    - /api/streams
    - /api/ws
    - /api/stream.m3u8
    - /api/hls/playlist.m3u8
    - /api/hls/segment.ts
    - /api/hls/init.mp4
    - /api/hls/segment.m4s
    - /api/stream.mjpeg
    - /api/frame.jpeg

streams:
  printer-usb-camera:
    - http://127.0.0.1:8556/stream
    - http://127.0.0.1:8080/stream
  labacam-01: "rtsp://admin:${LABACAM_PASSWORD}@192.168.0.138:554/profile1"

log:
  format: json
  level: warn
  output: stdout
