app:
  modules: [api, ws, http, mjpeg]

api:
  listen: "100.69.168.10:1984"
  username: "laba-vps"
  password: ${GO2RTC_API_PASSWORD}
  local_auth: true
  allow_paths:
    - /api/streams
    - /api/ws
    - /api/stream.mjpeg
    - /api/frame.jpeg

streams:
  printer-usb-camera: http://127.0.0.1:8080/stream

log:
  format: json
  level: warn
  output: stdout
